### ISSUE TITLE
Import error of API/Models folders

### ISSUE THREAD

**Issue by knowyrrole101** [BendingSpoons/searchads-api#12]
I tried installing library via pip and it installs fine...but I cant run this without getting an error as follows. I simply followed basic sample of from search_ads import SearchAds:

/anaconda/lib/python2.7/site-packages/search_ads/api/search_ads_building_blocks.py", line 7, in 
from api.utils import api_get

The library looks to be properly installed but gets an error referencing the api and models folder. Any idea how to solve this?

**Comment by knowyrrole101** [comment]
I figured out what the issue was....so it turns out in search_ads_building_blocks.py there is an error where you aren't calling search_ads.api.utils but instead just api.utils which throws the error above.

**Comment by haoshuncheng** [comment]
ImportError: No module named api.utils

**Comment by luke14free** [comment]
this should now be fixed, feel free to reopen if you still experience the issue
